-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE app_users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	auth_id TEXT,
	email TEXT,
	name TEXT,
	role TEXT DEFAULT 'user',
	created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assets (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	filename TEXT NOT NULL,
	url TEXT NOT NULL,
	size INTEGER,
	mime_type TEXT,
	uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE devices (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	model TEXT,
	name TEXT NOT NULL,
	description TEXT,
	color TEXT,
	storage TEXT,
	price TEXT,
	image_url TEXT,
	quantity INTEGER DEFAULT 1,
	created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE orders (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	order_number TEXT NOT NULL UNIQUE,
	tracking_number TEXT UNIQUE,
	device_id INTEGER,
	user_id INTEGER,
	customer_name TEXT,
	customer_email TEXT,
	shipping_address TEXT,
	waybill TEXT,
	package_dimensions TEXT,
	sender_info TEXT,
	receiver_info TEXT,
	status TEXT DEFAULT 'processing',
	created_at TEXT DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (device_id) REFERENCES devices(id),
    FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE TABLE tracking_events (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	order_id INTEGER NOT NULL,
	package_id INTEGER DEFAULT 0,
	date TEXT,
	location TEXT,
	description TEXT,
	created_at TEXT DEFAULT CURRENT_TIMESTAMP, status TEXT DEFAULT 'pending', timestamp TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- INDEXS

CREATE UNIQUE INDEX app_users_pkey ON app_users (id);

CREATE UNIQUE INDEX assets_pkey ON assets (id);

CREATE UNIQUE INDEX devices_pkey ON devices (id);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE UNIQUE INDEX orders_order_number_unique ON orders (order_number);

CREATE UNIQUE INDEX orders_pkey ON orders (id);

CREATE UNIQUE INDEX orders_tracking_number_unique ON orders (tracking_number);

CREATE UNIQUE INDEX tracking_events_pkey ON tracking_events (id);
