// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const appUsers = sqliteTable("app_users", {
	id: integer().primaryKey({ autoIncrement: true }),
	authId: text("auth_id"),
	email: text(),
	name: text(),
	role: text().default("user"),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`"),
},
(table) => [
	uniqueIndex("app_users_pkey").on(table.id),
]);

export const assets = sqliteTable("assets", {
	id: integer().primaryKey({ autoIncrement: true }),
	filename: text().notNull(),
	url: text().notNull(),
	size: integer(),
	mimeType: text("mime_type"),
	uploadedAt: text("uploaded_at").default("sql`(CURRENT_TIMESTAMP)`"),
},
(table) => [
	uniqueIndex("assets_pkey").on(table.id),
]);

export const devices = sqliteTable("devices", {
	id: integer().primaryKey({ autoIncrement: true }),
	model: text(),
	name: text().notNull(),
	description: text(),
	color: text(),
	storage: text(),
	price: text(),
	imageUrl: text("image_url"),
	quantity: integer().default(1),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`"),
},
(table) => [
	uniqueIndex("devices_pkey").on(table.id),
]);

export const orders = sqliteTable("orders", {
	id: integer().primaryKey({ autoIncrement: true }),
	orderNumber: text("order_number").notNull(),
	trackingNumber: text("tracking_number"),
	deviceId: integer("device_id").references(() => devices.id),
	userId: integer("user_id").references(() => appUsers.id),
	customerName: text("customer_name"),
	customerEmail: text("customer_email"),
	shippingAddress: text("shipping_address"),
	waybill: text(),
	packageDimensions: text("package_dimensions"),
	senderInfo: text("sender_info"),
	receiverInfo: text("receiver_info"),
	status: text().default("processing"),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`"),
	updatedAt: text("updated_at").default("sql`(CURRENT_TIMESTAMP)`"),
},
(table) => [
	uniqueIndex("orders_tracking_number_unique").on(table.trackingNumber),
	uniqueIndex("orders_pkey").on(table.id),
	uniqueIndex("orders_order_number_unique").on(table.orderNumber),
]);

export const trackingEvents = sqliteTable("tracking_events", {
	id: integer().primaryKey({ autoIncrement: true }),
	orderId: integer("order_id").notNull().references(() => orders.id),
	packageId: integer("package_id").default(0),
	date: text(),
	location: text(),
	description: text(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`"),
	status: text().default("pending"),
	timestamp: text().default("sql`(CURRENT_TIMESTAMP)`"),
},
(table) => [
	uniqueIndex("tracking_events_pkey").on(table.id),
]);

