-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE app_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  auth_id TEXT UNIQUE,
  email TEXT NOT NULL,
  name TEXT,
  role TEXT DEFAULT 'user',
  created_at INTEGER
);

CREATE TABLE assets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  url TEXT NOT NULL,
  size INTEGER,
  mime_type TEXT,
  uploaded_at INTEGER
);

CREATE TABLE devices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  model TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  color TEXT DEFAULT 'On admin activation',
  storage TEXT DEFAULT 'On admin activation',
  price TEXT DEFAULT 'Sponsored',
  quantity INTEGER DEFAULT 1,
  image_url TEXT,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_number TEXT NOT NULL UNIQUE,
  tracking_number TEXT UNIQUE,
  device_id INTEGER NOT NULL REFERENCES devices(id),
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT,
  shipping_address TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  color TEXT,
  storage TEXT,
  quantity INTEGER DEFAULT 1,
  notes TEXT,
  created_at INTEGER DEFAULT (unixepoch()),
  updated_at INTEGER DEFAULT (unixepoch())
, user_id INTEGER REFERENCES app_users(id), waybill TEXT, sender_info TEXT, package_dimensions TEXT, receiver_info TEXT);

CREATE TABLE packages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tracking_number TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    sender TEXT,
    recipient TEXT,
    destination TEXT,
    estimated_delivery TEXT,
    created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE tracking_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    package_id INTEGER NOT NULL,
    date TEXT NOT NULL,
    location TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at INTEGER DEFAULT (unixepoch()), order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE
);

-- INDEXS

CREATE INDEX app_users_auth_id_idx ON app_users(auth_id);

CREATE INDEX app_users_email_idx ON app_users(email);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_events_package_id ON tracking_events(package_id);

CREATE INDEX idx_orders_order_number ON orders(order_number);

CREATE INDEX idx_orders_status ON orders(status);

CREATE INDEX idx_orders_tracking_number ON orders(tracking_number);

CREATE INDEX idx_packages_tracking_number ON packages(tracking_number);

CREATE INDEX idx_tracking_events_order_id ON tracking_events(order_id);
