// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const packages = sqliteTable("packages", {
	id: integer().primaryKey({ autoIncrement: true }),
	trackingNumber: text("tracking_number").notNull(),
	status: text().notNull(),
	sender: text(),
	recipient: text(),
	destination: text(),
	estimatedDelivery: text("estimated_delivery"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_packages_tracking_number").on(table.trackingNumber),
]);

export const trackingEvents = sqliteTable("tracking_events", {
	id: integer().primaryKey({ autoIncrement: true }),
	packageId: integer("package_id").notNull().references(() => packages.id, { onDelete: "cascade" } ),
	date: text().notNull(),
	location: text().notNull(),
	description: text().notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	orderId: integer("order_id").references(() => orders.id, { onDelete: "cascade" } ),
},
(table) => [
	index("idx_tracking_events_order_id").on(table.orderId),
	index("idx_events_package_id").on(table.packageId),
]);

export const devices = sqliteTable("devices", {
	id: integer().primaryKey({ autoIncrement: true }),
	model: text().notNull(),
	name: text().notNull(),
	description: text().notNull(),
	color: text().default("On admin activation"),
	storage: text().default("On admin activation"),
	price: text().default("Sponsored"),
	quantity: integer().default(1),
	imageUrl: text("image_url"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
});

export const orders = sqliteTable("orders", {
	id: integer().primaryKey({ autoIncrement: true }),
	orderNumber: text("order_number").notNull(),
	trackingNumber: text("tracking_number"),
	deviceId: integer("device_id").notNull().references(() => devices.id),
	customerName: text("customer_name").notNull(),
	customerEmail: text("customer_email"),
	customerPhone: text("customer_phone"),
	shippingAddress: text("shipping_address").notNull(),
	status: text().default("pending"),
	color: text(),
	storage: text(),
	quantity: integer().default(1),
	notes: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`),
	userId: integer("user_id").references(() => appUsers.id),
	waybill: text(),
	senderInfo: text("sender_info"),
	packageDimensions: text("package_dimensions"),
	receiverInfo: text("receiver_info"),
},
(table) => [
	index("idx_orders_status").on(table.status),
	index("idx_orders_tracking_number").on(table.trackingNumber),
	index("idx_orders_order_number").on(table.orderNumber),
]);

export const appUsers = sqliteTable("app_users", {
	id: integer().primaryKey({ autoIncrement: true }),
	authId: text("auth_id"),
	email: text().notNull(),
	name: text(),
	role: text().default("user"),
	createdAt: integer("created_at"),
},
(table) => [
	index("app_users_auth_id_idx").on(table.authId),
	index("app_users_email_idx").on(table.email),
]);

export const assets = sqliteTable("assets", {
	id: integer().primaryKey({ autoIncrement: true }),
	filename: text().notNull(),
	url: text().notNull(),
	size: integer(),
	mimeType: text("mime_type"),
	uploadedAt: integer("uploaded_at"),
});

