// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { packages, trackingEvents, orders, appUsers, devices } from "./db_schema";

export const trackingEventsRelations = relations(trackingEvents, ({one}) => ({
	package: one(packages, {
		fields: [trackingEvents.packageId],
		references: [packages.id]
	}),
	order: one(orders, {
		fields: [trackingEvents.orderId],
		references: [orders.id]
	}),
}));

export const packagesRelations = relations(packages, ({many}) => ({
	trackingEvents: many(trackingEvents),
}));

export const ordersRelations = relations(orders, ({one, many}) => ({
	trackingEvents: many(trackingEvents),
	appUser: one(appUsers, {
		fields: [orders.userId],
		references: [appUsers.id]
	}),
	device: one(devices, {
		fields: [orders.deviceId],
		references: [devices.id]
	}),
}));

export const appUsersRelations = relations(appUsers, ({many}) => ({
	orders: many(orders),
}));

export const devicesRelations = relations(devices, ({many}) => ({
	orders: many(orders),
}));
